-- 코드를 입력하세요
SELECT DISTINCT C.CAR_ID, C.CAR_TYPE, FLOOR((DAILY_FEE * (1 - DISCOUNT_RATE / 100) * 30)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY H, CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
WHERE C.CAR_ID = H.CAR_ID AND C.CAR_TYPE = P.CAR_TYPE AND (C.CAR_TYPE = "세단" OR C.CAR_TYPE = "SUV") AND 
C.CAR_ID NOT IN (select CAR_ID
                       from CAR_RENTAL_COMPANY_RENTAL_HISTORY
                       where END_DATE > '2022-11-00'
                       and START_DATE < '2022-12-00') AND DURATION_TYPE = "30일 이상" AND FLOOR((DAILY_FEE * (1 - DISCOUNT_RATE / 100) * 30)) >= 500000 AND FLOOR((DAILY_FEE * (1 - DISCOUNT_RATE / 100) * 30)) < 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC