-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES)  TOTAL_SALES
    FROM BOOK_SALES S, BOOK B
    WHERE S.BOOK_ID = B.BOOK_ID and YEAR(SALES_DATE) = 2022 and MONTH(SALES_DATE) = 1
    GROUP BY CATEGORY
    ORDER BY CATEGORY
        