-- 코드를 입력하세요
SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(SALES * PRICE) TOTAL_SALES
    FROM BOOK B, AUTHOR A, BOOK_SALES S
    WHERE B.AUTHOR_ID = A.AUTHOR_ID AND B.BOOK_ID = S.BOOK_ID AND SALES_DATE LIKE "2022-01%"
    GROUP BY B.AUTHOR_ID, B.CATEGORY
    ORDER BY AUTHOR_ID, CATEGORY DESC