-- 코드를 입력하세요
SELECT HISTORY_ID, ROUND((DATEDIFF(END_DATE,START_DATE) + 1) * DAILY_FEE * (1 - (CASE WHEN DATEDIFF(END_DATE,START_DATE) + 1 >= 90 THEN 0.15 WHEN DATEDIFF(END_DATE,START_DATE) + 1 >= 30 THEN 0.08 WHEN DATEDIFF(END_DATE,START_DATE) + 1 >= 7 THEN 0.05 ELSE 0.0 END)),0) FEE
    FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY H, CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    WHERE C.CAR_ID = H.CAR_ID AND C.CAR_TYPE = P.CAR_TYPE AND C.CAR_TYPE = "트럭"
    GROUP BY HISTORY_ID
    ORDER BY FEE DESC, HISTORY_ID DESC