-- 코드를 입력하세요
SELECT O.PRODUCT_ID, PRODUCT_NAME, (SUM(PRICE * AMOUNT)) TOTAL_SALES
    FROM FOOD_PRODUCT P, FOOD_ORDER O
    WHERE PRODUCE_DATE LIKE "2022-05%" AND P.PRODUCT_ID = O.PRODUCT_ID
    GROUP BY O.PRODUCT_ID
    ORDER BY TOTAL_SALES DESC, O.PRODUCT_ID