-- 코드를 입력하세요
SELECT APNT_NO, PT_NAME, P.PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
    FROM PATIENT P, DOCTOR D, APPOINTMENT A
    WHERE P.PT_NO = A.PT_NO AND MDDR_ID = DR_ID AND A.MCDP_CD = "CS" AND APNT_CNCL_YN ="N" AND APNT_YMD LIKE "2022-04-13%"
    ORDER BY APNT_YMD